[workspace]
resolver = "2"
members = ["crates/logi-wheel-core", "crates/logi-wheel-tui", "crates/logi-ffb", "crates/logi-wheel-gui", "crates/logi-tf-sim", "crates/logi-tf-scs", "crates/logi-tf-relay"]

[workspace.package]
edition = "2021"
rust-version = "1.74"
version = "0.29.0"
license = "GPL-2.0"
